### ISSUE TITLE
[review-apicontract] P2: org bulk-remove swallows repo error (200 masks wholesale failure) + status/pagination/return-shape drift families (R316)

### ISSUE THREAD

**Issue by topcheer** [topcheer/ggid#549]
Found R316 (sa-103 API-contract sweep; sa-104 verification: V4 CONFIRMED P2 upgrade-justified NEW; L1/L3/L4 confirmed as recorded P2 families; V5 partial - 3/4 sites confirmed, the :15 citation is not an error body, rest is the chronic error-format family).

(V4) P2 upgrade-candidate (fabricated-success family) - services/org/internal/server/http.go:1424 - bulk member REMOVE swallows the repo error verbatim: `removed, _ := s.memberSvc.RemoveByIDs(r.Context(), matched)` and the 200 response (status/removed/total_requested) carries no failed/errors field, while the sibling bulk ADD arm (:1366-1372) reports both `failed` and `errors`. A wholesale RemoveByIDs failure still yields 200 "completed". Introduced by the #482(B) R273 N+1 batch fix - not previously flagged. Fix shape: propagate the error (500 on wholesale failure) and/or report partial failure like the add arm.

Recorded P2 families (verified verbatim by sa-103, low individual severity, fix opportunistically):
(L1) status drift within resource families: org bulk add 201 (http.go:1366) vs bulk remove 200 (:1426); auth attrMappingDelete 204 (attr_mapping_handler.go:190) vs delegationRevoke 200+body (delegation_handler.go:228).
(L3) pagination convention split: audit accepts both page/page_size AND limit/offset across handlers (activity_handler.go:21 page_size-only; incident_handler.go:98 offset/limit; tamper_check_handler.go:48 limit-only); identity tenant_handlers.go:552 page/page_size vs smart_search_handler.go:73 + hr_connector_handler.go:269 limit-only; policy http.go:890 parsePagination vs :2567 bare limit; oauth server.go:2011 offset/limit.
(L4) mutation return-shape drift within families: policy JIT create 201 full object (jit_handler.go:139) vs approve/reject/revoke 200 {"status"} (:275/:311/:366); auth four shapes across rotation 201 / attr_mapping 204 / delegation {"status","id"} / session_revoke {"revoked_count","failed"}; org bulk add vs remove body asymmetry (part of V4).
(V5) oauth error-body drift: 3 inline schemas + wrapper confirmed (server.go:501 RFC error/error_description; :581 error/detail; client_deprecation_handler.go:42 error-only prose; writeJSONError wrapper elsewhere) - instance of the chronic repo-wide error-format family (R300/R327); the originally cited oauth21_audit_handler.go:15 is a compliance DTO field, not an error body.

**Comment by topcheer** [comment]
V4 landed in b09f8536e (R316): bulk-remove propagates the RemoveByIDs error as 500 instead of 200-completed. The envelope asymmetry (no failed/errors on remove) + L1/L3/L4 drift families remain recorded legs here.

**Comment by topcheer** [comment]
R35 sa-135 same-family addendum (recorded, not a new issue): the bulk-ADD arm (http.go:1504-1533) has the V4 mirror problem - unconditional 201 + status:completed even when added=0/failed=N (total failure), and per-item errors collapse to literal 'import failed' hiding the real cause (a #790 NotFound is indistinguishable from a DB outage). Same fabricated-success family as V4; fix opportunistically with the L4 body-asymmetry leg.
